const products = [
  {
    id: 1,
    name: "Remera Negra",
    price: 2000,
    stock: 35,
    category: "Remera",
    src: "../img/remeraNegra.jpg",
  },
  {
    id: 2,
    name: "Remera Blanca",
    price: 2000,
    stock: 40,
    category: "Remera",
    src: "../img/remeraBlanca.jpg",
  },
  {
    id: 3,
    name: "Remera Amarilla",
    price: 2000,
    stock: 50,
    category: "Remera",
    src: "../img/remeraAmarilla.jpg",
  },
  {
    id: 4,
    name: "Remera Azul",
    price: 2000,
    stock: 38,
    category: "Remera",
    src: "../img/remeraAzul.jpg",
  },
  {
    id: 5,
    name: "Remera Roja",
    price: 2000,
    stock: 45,
    category: "Remera",
    src: "../img/remeraRoja.jpg",
  },
  {
    id: 6,
    name: "Buzo Azul",
    price: 3000,
    stock: 35,
    category: "Buzo",
    src: "../img/buzoAzul.jpg",
  },
  {
    id: 7,
    name: "Buzo Celeste",
    price: 3000,
    stock: 40,
    category: "Buzo",
    src: "../img/buzoCeleste.jpg",
  },
  {
    id: 8,
    name: "Buzo Gris",
    price: 3000,
    stock: 20,
    category: "Buzo",
    src: "../img/buzoGris.jpg",
  },
  {
    id: 9,
    name: "Buzo Negro",
    price: 3000,
    stock: 35,
    category: "Buzo",
    src: "../img/buzoNegro.jpg",
  },
  {
    id: 10,
    name: "Buzo Verde",
    price: 3000,
    stock: 50,
    category: "Buzo",
    src: "../img/buzoVerde.jpg",
  },
  {
    id: 11,
    name: "Gorra Australia",
    price: 1600,
    stock: 50,
    category: "Gorra",
    src: "../img/gorraAustralia.jpg",
  },
  {
    id: 12,
    name: "Gorra Beisbol",
    price: 1600,
    stock: 50,
    category: "Gorra",
    src: "../img/gorraBeisbol.jpg",
  },
  {
    id: 13,
    name: "Gorra Manchester",
    price: 1600,
    stock: 50,
    category: "Gorra",
    src: "../img/gorraManchester.jpg",
  },
  {
    id: 14,
    name: "Gorra NY",
    price: 1600,
    stock: 50,
    category: "Gorra",
    src: "../img/gorraNY.jpg",
  },
  {
    id: 15,
    name: "Gorra Running",
    price: 1600,
    stock: 50,
    category: "Gorra",
    src: "../img/gorraRunning.jpg",
  },
];

export default products;
